#!/usr/bin/env python
# _*_ coding:utf-8 _*_
#
# @Version : 1.0
# @Time    : 2021/08/02
# @Author  : zl
# @File    : 
#
# A dice for the TRPG Magicalogia.
# Feature:
# 1. Obtaining Dice roll result of D66 (which is 2d6 in a different expression).
# 2. Presenting automatic attack/defend in magic battle 
#    (3 ways: all random, Central Attack/Defence, Column Attack)
# 3. Selecting random skills and calculating skill gap. 
# 4. Storing PC cards. 
